/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as PortalProfileRouteImport } from './routes/portal/profile'
import { Route as PortalDevicesRouteImport } from './routes/portal/devices'
import { Route as PortalDashboardRouteImport } from './routes/portal/dashboard'
import { Route as AuthSetPasswordRouteImport } from './routes/auth.set-password'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as Auth2faChallengeRouteImport } from './routes/auth.2fa-challenge'
import { Route as AppTicketsRouteImport } from './routes/_app/tickets'
import { Route as AppScriptsRouteImport } from './routes/_app/scripts'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppKanbanRouteImport } from './routes/_app/kanban'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppDocsRouteImport } from './routes/_app/docs'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCostsRouteImport } from './routes/_app/costs'
import { Route as AppContactsRouteImport } from './routes/_app/contacts'
import { Route as AppClientsRouteImport } from './routes/_app/clients'
import { Route as AppChecklistRouteImport } from './routes/_app/checklist'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppBundlesRouteImport } from './routes/_app/bundles'
import { Route as AppAutomationsRouteImport } from './routes/_app/automations'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as PortalTicketsIndexRouteImport } from './routes/portal/tickets/index'
import { Route as PortalDocumentsIndexRouteImport } from './routes/portal/documents/index'
import { Route as PortalTicketsNewRouteImport } from './routes/portal/tickets/new'
import { Route as PortalTicketsTicketIdRouteImport } from './routes/portal/tickets/$ticketId'
import { Route as AppTicketsArchiveRouteImport } from './routes/_app/tickets_.archive'
import { Route as AppOauthConsentRouteImport } from './routes/_app/oauth.consent'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDevicesRoute = PortalDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PortalRoute,
} as any)
const AuthSetPasswordRoute = AuthSetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const Auth2faChallengeRoute = Auth2faChallengeRouteImport.update({
  id: '/2fa-challenge',
  path: '/2fa-challenge',
  getParentRoute: () => AuthRoute,
} as any)
const AppTicketsRoute = AppTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AppRoute,
} as any)
const AppScriptsRoute = AppScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppKanbanRoute = AppKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppDocsRoute = AppDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCostsRoute = AppCostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppChecklistRoute = AppChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppBundlesRoute = AppBundlesRouteImport.update({
  id: '/bundles',
  path: '/bundles',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationsRoute = AppAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const PortalTicketsIndexRoute = PortalTicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDocumentsIndexRoute = PortalDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTicketsNewRoute = PortalTicketsNewRouteImport.update({
  id: '/tickets/new',
  path: '/tickets/new',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTicketsTicketIdRoute = PortalTicketsTicketIdRouteImport.update({
  id: '/tickets/$ticketId',
  path: '/tickets/$ticketId',
  getParentRoute: () => PortalRoute,
} as any)
const AppTicketsArchiveRoute = AppTicketsArchiveRouteImport.update({
  id: '/tickets_/archive',
  path: '/tickets/archive',
  getParentRoute: () => AppRoute,
} as any)
const AppOauthConsentRoute = AppOauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/auth': typeof AuthRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/admin': typeof AppAdminRoute
  '/automations': typeof AppAutomationsRoute
  '/bundles': typeof AppBundlesRoute
  '/calendar': typeof AppCalendarRoute
  '/checklist': typeof AppChecklistRoute
  '/clients': typeof AppClientsRoute
  '/contacts': typeof AppContactsRoute
  '/costs': typeof AppCostsRoute
  '/dashboard': typeof AppDashboardRoute
  '/docs': typeof AppDocsRoute
  '/inventory': typeof AppInventoryRoute
  '/kanban': typeof AppKanbanRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/scripts': typeof AppScriptsRoute
  '/tickets': typeof AppTicketsRoute
  '/auth/2fa-challenge': typeof Auth2faChallengeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/devices': typeof PortalDevicesRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/': typeof PortalIndexRoute
  '/oauth/consent': typeof AppOauthConsentRoute
  '/tickets/archive': typeof AppTicketsArchiveRoute
  '/portal/tickets/$ticketId': typeof PortalTicketsTicketIdRoute
  '/portal/tickets/new': typeof PortalTicketsNewRoute
  '/portal/documents/': typeof PortalDocumentsIndexRoute
  '/portal/tickets/': typeof PortalTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/auth': typeof AuthRouteWithChildren
  '/admin': typeof AppAdminRoute
  '/automations': typeof AppAutomationsRoute
  '/bundles': typeof AppBundlesRoute
  '/calendar': typeof AppCalendarRoute
  '/checklist': typeof AppChecklistRoute
  '/clients': typeof AppClientsRoute
  '/contacts': typeof AppContactsRoute
  '/costs': typeof AppCostsRoute
  '/dashboard': typeof AppDashboardRoute
  '/docs': typeof AppDocsRoute
  '/inventory': typeof AppInventoryRoute
  '/kanban': typeof AppKanbanRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/scripts': typeof AppScriptsRoute
  '/tickets': typeof AppTicketsRoute
  '/auth/2fa-challenge': typeof Auth2faChallengeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/devices': typeof PortalDevicesRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal': typeof PortalIndexRoute
  '/oauth/consent': typeof AppOauthConsentRoute
  '/tickets/archive': typeof AppTicketsArchiveRoute
  '/portal/tickets/$ticketId': typeof PortalTicketsTicketIdRoute
  '/portal/tickets/new': typeof PortalTicketsNewRoute
  '/portal/documents': typeof PortalDocumentsIndexRoute
  '/portal/tickets': typeof PortalTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/_app/admin': typeof AppAdminRoute
  '/_app/automations': typeof AppAutomationsRoute
  '/_app/bundles': typeof AppBundlesRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/checklist': typeof AppChecklistRoute
  '/_app/clients': typeof AppClientsRoute
  '/_app/contacts': typeof AppContactsRoute
  '/_app/costs': typeof AppCostsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/docs': typeof AppDocsRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/kanban': typeof AppKanbanRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/scripts': typeof AppScriptsRoute
  '/_app/tickets': typeof AppTicketsRoute
  '/auth/2fa-challenge': typeof Auth2faChallengeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/devices': typeof PortalDevicesRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/': typeof PortalIndexRoute
  '/_app/oauth/consent': typeof AppOauthConsentRoute
  '/_app/tickets_/archive': typeof AppTicketsArchiveRoute
  '/portal/tickets/$ticketId': typeof PortalTicketsTicketIdRoute
  '/portal/tickets/new': typeof PortalTicketsNewRoute
  '/portal/documents/': typeof PortalDocumentsIndexRoute
  '/portal/tickets/': typeof PortalTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/auth'
    | '/portal'
    | '/admin'
    | '/automations'
    | '/bundles'
    | '/calendar'
    | '/checklist'
    | '/clients'
    | '/contacts'
    | '/costs'
    | '/dashboard'
    | '/docs'
    | '/inventory'
    | '/kanban'
    | '/notifications'
    | '/profile'
    | '/scripts'
    | '/tickets'
    | '/auth/2fa-challenge'
    | '/auth/callback'
    | '/auth/set-password'
    | '/portal/dashboard'
    | '/portal/devices'
    | '/portal/profile'
    | '/portal/'
    | '/oauth/consent'
    | '/tickets/archive'
    | '/portal/tickets/$ticketId'
    | '/portal/tickets/new'
    | '/portal/documents/'
    | '/portal/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/auth'
    | '/admin'
    | '/automations'
    | '/bundles'
    | '/calendar'
    | '/checklist'
    | '/clients'
    | '/contacts'
    | '/costs'
    | '/dashboard'
    | '/docs'
    | '/inventory'
    | '/kanban'
    | '/notifications'
    | '/profile'
    | '/scripts'
    | '/tickets'
    | '/auth/2fa-challenge'
    | '/auth/callback'
    | '/auth/set-password'
    | '/portal/dashboard'
    | '/portal/devices'
    | '/portal/profile'
    | '/portal'
    | '/oauth/consent'
    | '/tickets/archive'
    | '/portal/tickets/$ticketId'
    | '/portal/tickets/new'
    | '/portal/documents'
    | '/portal/tickets'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_app'
    | '/auth'
    | '/portal'
    | '/_app/admin'
    | '/_app/automations'
    | '/_app/bundles'
    | '/_app/calendar'
    | '/_app/checklist'
    | '/_app/clients'
    | '/_app/contacts'
    | '/_app/costs'
    | '/_app/dashboard'
    | '/_app/docs'
    | '/_app/inventory'
    | '/_app/kanban'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/scripts'
    | '/_app/tickets'
    | '/auth/2fa-challenge'
    | '/auth/callback'
    | '/auth/set-password'
    | '/portal/dashboard'
    | '/portal/devices'
    | '/portal/profile'
    | '/portal/'
    | '/_app/oauth/consent'
    | '/_app/tickets_/archive'
    | '/portal/tickets/$ticketId'
    | '/portal/tickets/new'
    | '/portal/documents/'
    | '/portal/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/devices': {
      id: '/portal/devices'
      path: '/devices'
      fullPath: '/portal/devices'
      preLoaderRoute: typeof PortalDevicesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/dashboard': {
      id: '/portal/dashboard'
      path: '/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/auth/set-password': {
      id: '/auth/set-password'
      path: '/set-password'
      fullPath: '/auth/set-password'
      preLoaderRoute: typeof AuthSetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/2fa-challenge': {
      id: '/auth/2fa-challenge'
      path: '/2fa-challenge'
      fullPath: '/auth/2fa-challenge'
      preLoaderRoute: typeof Auth2faChallengeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/tickets': {
      id: '/_app/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AppTicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scripts': {
      id: '/_app/scripts'
      path: '/scripts'
      fullPath: '/scripts'
      preLoaderRoute: typeof AppScriptsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kanban': {
      id: '/_app/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AppKanbanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/docs': {
      id: '/_app/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AppDocsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/costs': {
      id: '/_app/costs'
      path: '/costs'
      fullPath: '/costs'
      preLoaderRoute: typeof AppCostsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts': {
      id: '/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checklist': {
      id: '/_app/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof AppChecklistRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bundles': {
      id: '/_app/bundles'
      path: '/bundles'
      fullPath: '/bundles'
      preLoaderRoute: typeof AppBundlesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automations': {
      id: '/_app/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AppAutomationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/portal/tickets/': {
      id: '/portal/tickets/'
      path: '/tickets'
      fullPath: '/portal/tickets/'
      preLoaderRoute: typeof PortalTicketsIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/documents/': {
      id: '/portal/documents/'
      path: '/documents'
      fullPath: '/portal/documents/'
      preLoaderRoute: typeof PortalDocumentsIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/tickets/new': {
      id: '/portal/tickets/new'
      path: '/tickets/new'
      fullPath: '/portal/tickets/new'
      preLoaderRoute: typeof PortalTicketsNewRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/tickets/$ticketId': {
      id: '/portal/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/portal/tickets/$ticketId'
      preLoaderRoute: typeof PortalTicketsTicketIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_app/tickets_/archive': {
      id: '/_app/tickets_/archive'
      path: '/tickets/archive'
      fullPath: '/tickets/archive'
      preLoaderRoute: typeof AppTicketsArchiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/oauth/consent': {
      id: '/_app/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof AppOauthConsentRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAutomationsRoute: typeof AppAutomationsRoute
  AppBundlesRoute: typeof AppBundlesRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppChecklistRoute: typeof AppChecklistRoute
  AppClientsRoute: typeof AppClientsRoute
  AppContactsRoute: typeof AppContactsRoute
  AppCostsRoute: typeof AppCostsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocsRoute: typeof AppDocsRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppKanbanRoute: typeof AppKanbanRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppScriptsRoute: typeof AppScriptsRoute
  AppTicketsRoute: typeof AppTicketsRoute
  AppOauthConsentRoute: typeof AppOauthConsentRoute
  AppTicketsArchiveRoute: typeof AppTicketsArchiveRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAutomationsRoute: AppAutomationsRoute,
  AppBundlesRoute: AppBundlesRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppChecklistRoute: AppChecklistRoute,
  AppClientsRoute: AppClientsRoute,
  AppContactsRoute: AppContactsRoute,
  AppCostsRoute: AppCostsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocsRoute: AppDocsRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppKanbanRoute: AppKanbanRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppScriptsRoute: AppScriptsRoute,
  AppTicketsRoute: AppTicketsRoute,
  AppOauthConsentRoute: AppOauthConsentRoute,
  AppTicketsArchiveRoute: AppTicketsArchiveRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  Auth2faChallengeRoute: typeof Auth2faChallengeRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthSetPasswordRoute: typeof AuthSetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  Auth2faChallengeRoute: Auth2faChallengeRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthSetPasswordRoute: AuthSetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PortalRouteChildren {
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalDevicesRoute: typeof PortalDevicesRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalTicketsTicketIdRoute: typeof PortalTicketsTicketIdRoute
  PortalTicketsNewRoute: typeof PortalTicketsNewRoute
  PortalDocumentsIndexRoute: typeof PortalDocumentsIndexRoute
  PortalTicketsIndexRoute: typeof PortalTicketsIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalDashboardRoute: PortalDashboardRoute,
  PortalDevicesRoute: PortalDevicesRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalTicketsTicketIdRoute: PortalTicketsTicketIdRoute,
  PortalTicketsNewRoute: PortalTicketsNewRoute,
  PortalDocumentsIndexRoute: PortalDocumentsIndexRoute,
  PortalTicketsIndexRoute: PortalTicketsIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
