// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import { queryClient } from "@/lib/queries/queryClient";
import type { Database } from "./types";

/**
 *
 */
export type RealtimeConnectionStatus = "connected" | "connecting" | "disconnected";

type RealtimeConnectionListener = () => void;

let realtimeConnectionStatus: RealtimeConnectionStatus = "connected";
const realtimeConnectionListeners = new Set<RealtimeConnectionListener>();

/**
 *
 */
export function getRealtimeConnectionStatus() {
  return realtimeConnectionStatus;
}

/**
 *
 */
export function subscribeRealtimeConnectionStatus(listener: RealtimeConnectionListener) {
  realtimeConnectionListeners.add(listener);

  return () => {
    realtimeConnectionListeners.delete(listener);
  };
}

/**
 *
 */
export function setRealtimeConnectionStatus(status: RealtimeConnectionStatus) {
  if (realtimeConnectionStatus === status) return;
  realtimeConnectionStatus = status;
  realtimeConnectionListeners.forEach((listener) => listener());
}

function handleRealtimeConnected() {
  const wasDisconnected = realtimeConnectionStatus === "disconnected";
  setRealtimeConnectionStatus("connected");

  if (wasDisconnected) {
    void queryClient.refetchQueries({ type: "active" });
  }
}

function handleRealtimeDisconnected() {
  setRealtimeConnectionStatus("disconnected");
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Set them in .env.local (see .env.example).`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  // Security: prefer `sessionStorage` over `localStorage` for auth tokens
  // Tokens stored in `localStorage` are accessible from any JS running
  // on the page, which amplifies the impact of an XSS vulnerability.
  // Using `sessionStorage` limits the lifetime to the tab session and
  // reduces exposure. For stronger protection, consider HttpOnly
  // cookies via server-side auth or enforce a robust CSP.
  const client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      // Use sessionStorage in browser environments to reduce XSS impact.
      storage: typeof window !== "undefined" ? sessionStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
    realtime: {
      worker: typeof window !== "undefined",
    },
  });

  client.realtime.stateChangeCallbacks.open.push([
    "pcready:realtime-open",
    () => {
      console.log("[realtime] Connesso");
      handleRealtimeConnected();
    },
  ]);

  client.realtime.stateChangeCallbacks.close.push([
    "pcready:realtime-close",
    () => {
      console.warn("[realtime] Disconnesso");
      handleRealtimeDisconnected();
    },
  ]);

  client.realtime.stateChangeCallbacks.error.push([
    "pcready:realtime-error",
    (error: unknown) => {
      console.error("[realtime] Errore:", error);
      handleRealtimeDisconnected();
    },
  ]);

  client.realtime.onHeartbeat((status) => {
    if (status === "ok") {
      handleRealtimeConnected();
      return;
    }

    if (status === "timeout" || status === "disconnected" || status === "error") {
      handleRealtimeDisconnected();
      client.realtime.connect();
    }
  });

  if (typeof window !== "undefined") {
    window.addEventListener("offline", handleRealtimeDisconnected);
    window.addEventListener("online", () => {
      setRealtimeConnectionStatus("connecting");
      client.realtime.connect();
    });
  }

  return client;
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
